### ISSUE TITLE
Got some trouble with install

### ISSUE THREAD

**Issue by AlanHuang1998** [aimagelab/speaksee#5]
Thanks for sharing,
I got ERROR when I install the requirement torch, the situation is the same as seen in the photo.
![1572056935437](https://user-images.githubusercontent.com/36326341/67613053-7edfb780-f7db-11e9-8405-f369c81d46e3.jpg)

Is there any way to solve it?

**Comment by tejasri19** [comment]
@baraldilorenzo I got library error as below. Please help!
![image](https://user-images.githubusercontent.com/22271616/80284148-4729dc00-873a-11ea-8ad8-2d97d1271a3d.png)
